name: Map generation

on:
    workflow_dispatch:


jobs:
    build:
        runs-on: ubuntu-22.04-16core

        steps:
            - name: Checkout
              uses: actions/checkout@v3


            - name: Build Docker Image
              run: docker build . -t map_gen:1.0.0

            - name: Run Docker Image
              run: |
                    while IFS="," read -r name coordinates_w coordinates_s coordinates_e coordinates_n lod type storage blender_storage
                    do
                        docker run -v ~/.simulation-gazebo/worlds/:/work/output --rm map_gen:1.0.0 \
                        python3 map_generation.py \
                        --coordinates "$coordinates_w,$coordinates_s,$coordinates_e,$coordinates_n" \
                        --lod "$lod" \
                        --google_api_key "${{ secrets.GOOGLE_API_KEY }}" \
                        --data_type "$type" \
                        --name "$name" \
                        --world_store "$storage" \
                        --blender_store "$blender_storage"
                    done < first_round_map_generation.csv
              continue-on-error: true

            - name: Upload maps
              uses: actions/upload-artifact@v2
              with:
                name: maps_first_set
                path: ~/.simulation-gazebo/worlds/
