name: Map generation

on:
    workflow_dispatch:


jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3


            - name: Build Docker Image
              run: docker build . -t map_gen:1.0.0

            - name: Run Docker Image
              run: |
                    while IFS="," read -r name coordinates_w coordinates_s coordinates_e coordinates_n lod type storage blender_storage
                    do
                        docker run -v ~/.simulation-gazebo/worlds/:/work/output --rm \
                        -e COORDINATES="$coordinates_w,$coordinates_s,$coordinates_e,$coordinates_n" \
                        -e LOD="$lod" \
                        -e GOOGLE_API_KEY="${{ secrets.GOOGLE_API_KEY }}" \
                        -e DATA_TYPE="$type" \
                        -e NAME="$name" \
                        -e WORLD_STORE="$storage" \
                        -e BLENDER_STORE="$blender_storage" \
                        map_gen:1.0.0
                    done < first_round_map_generation.csv

            - name: Upload maps
              uses: actions/upload-artifact@v2
              with:
                name: maps_first_set
                path: ~/.simulation-gazebo/worlds/
